### PR TITLE
List Tamadcoin (TMC)

### PR DESCRIPTION
**Pull request by jared201**
- Official block explorer URL: https://tamadcoin.io/explorer
- Is this an _altcoin_ with a dedicated blockchain or a _token_ based on another blockchain, (e.g. Ethereum-based ERC-20 tokens): altcoin
- Official project URL: https://tamadcoin.io

### CODE REVIEW

**Comment by blabno** [comment]
Yes Jared, @cbeams is working on new documentation.

**Comment by jared201** [comment]
@blabno @cbeams 

https://forum.bisq.network/t/how-to-add-your-favorite-altcoin/ site can't be reached

**Comment by blabno** [comment]
Meanwhile have a look at this: https://github.com/bisq-network/bisq-core/commit/97584a79a431813278aa531f992bd0fcb2ca9906

**Comment by jared201** [comment]
cancelling this pull request for the updated altcoin rebase

**Comment by cbeams** [comment]
The process for listing an asset has recently changed (see #32), and I am now closing this pull request along with all other outstanding asset listing pull requests.

Please read and follow the new instructions at https://bisq.network/list-asset and re-submit a new pull request when ready. Note that Bisq v0.7.0 will likely ship within the next week, so you should still be able to get your asset listed in time for that release. Thanks.

**Pull request closed without merging**
